included:
  - Weather App
  - Weather AppTests
  - Weather AppUITests

excluded:
  - Carthage
  - Pods
  - DerivedData
  - .build
  - Weather App/Configuration/Config.plist

analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_arrow_whitespace
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

disabled_rules:
  - trailing_whitespace
  - line_length
  - file_length
  - type_body_length
  - function_body_length

line_length:
  warning: 150
  error: 200

identifier_name:
  excluded:
    - id
    - URL
    - dt

force_cast: warning
force_try: warning

type_name:
  min_length: 3
  max_length: 50

file_header:
  required_pattern: |
    \/\/
    \/\/  .*\.swift
    \/\/  Weather App
    \/\/
    \/\/  Created by .* on \d{4}\/\d{2}\/\d{2}\.
    \/\/

custom_rules:
  no_hardcoded_strings:
    name: "No Hardcoded API Keys"
    regex: '(AIza[0-9A-Za-z-_]{35}|[0-9a-f]{32})'
    message: "API keys should not be hardcoded"
    severity: error
